export interface ClassDefinition {
  name: string;
  description: string;
}

export const CLASS_CATALOG: ClassDefinition[] = [
  { name: 'Abjurer', description: 'A wizard specializing in protective and defensive magic.' },
  { name: 'Acrobat', description: 'A nimble, acrobatic rogue archetype focused on evasion and mobility.' },
  { name: 'Alchemist', description: 'A master of chemistry and transmutation who creates powerful potions, bombs, and elixirs.' },
  { name: 'Amazon', description: 'A fierce female warrior, often associated with bows, spears, and mounted combat.' },
  { name: 'Animist', description: 'A caster who channels the souls of animals and spirits.' },
  { name: 'Arbalist', description: 'A crossbow specialist, often a variant of the archer or engineer.' },
  { name: 'Arcane Archer', description: 'A magical archer who enhances arrows with spells.' },
  { name: 'Arcanist', description: 'A versatile arcane spellcaster who studies magic using arcane points.' },
  { name: 'Archer', description: 'A ranged physical damage dealer specialized in bows and precision.' },
  { name: 'Armorer', description: 'A crafter who forges and maintains metal armor and shields.' },
  { name: 'Artificer', description: 'A master of magical invention who creates and modifies magical items and devices.' },
  { name: 'Assassin', description: 'A stealthy killer who excels at ambushes, poisons, and dealing single-target damage from the shadows.' },
  { name: 'Astrologian', description: 'A fate-weaving mage who uses the stars to heal, buff, or damage.' },
  { name: 'Barbarian', description: 'A powerful, rage-fueled damage dealer who often neglects armor for sheer offensive power.' },
  { name: 'Bard', description: 'A versatile musician and trickster who supports the party with songs and magical enchantments.' },
  { name: 'Battlemage', description: 'A hybrid class blending melee combat with offensive spells, often wearing heavy armor.' },
  { name: 'Beastmaster', description: 'A hunter who fights alongside a loyal animal companion.' },
  { name: 'Berserker', description: 'A frenzied damage-dealer, similar to a Barbarian, who trades defense for raw aggression.' },
  { name: 'Black Mage', description: 'An offensive spellcaster who masters destructive elemental magic.' },
  { name: 'Blackguard', description: 'An evil-aligned counterpart to the Paladin, wielding dark powers.' },
  { name: 'Blacksmith', description: 'A craftsperson who forges weapons and armor from raw materials.' },
  { name: 'Bladedancer', description: 'An agile warrior who uses elegant, dance-like sword attacks.' },
  { name: 'Blood Mage', description: 'A dangerous spellcaster who uses blood as a focus for powerful, often forbidden, magic.' },
  { name: 'Bounty Hunter', description: 'A skilled tracker who specializes in capturing or eliminating specific targets.' },
  { name: 'Brute', description: 'A tough melee fighter focusing on overwhelming physical force.' },
  { name: 'Buccaneer', description: 'A swashbuckling warrior and rogue mix focused on charm and agility.' },
  { name: 'Burglar', description: 'A stealth specialist focused on lock-picking and trap-disarming.' },
  { name: 'Cabalist', description: 'A dark caster who commands forbidden magic and curses.' },
  { name: 'Cannoneer', description: 'A heavy weapons expert who uses cannons and explosives.' },
  { name: 'Cavalier', description: 'A mounted knight who charges into battle with lance and shield.' },
  { name: 'Champion', description: 'A holy warrior who defends allies and smites enemies.' },
  { name: 'Channeler', description: 'A mage who channels raw magic from external sources.' },
  { name: 'Chemist', description: 'A non-magical healer who uses medicine and tools.' },
  { name: 'Cleric', description: 'A divine spellcaster who specializes in healing and support, often wielding maces and wearing armor.' },
  { name: 'Conjurer', description: 'A summoning wizard who calls forth creatures and objects from other planes.' },
  { name: 'Corsair', description: 'A pirate-themed rogue who wields cutlasses and pistols.' },
  { name: 'Crusader', description: 'A holy warrior less strict than a Paladin but more offensive than a Cleric.' },
  { name: 'Curate', description: 'A divine healer focused purely on mending wounds.' },
  { name: 'Dark Knight', description: 'A gloom-cloaked knight sacrificing health for devastating dark power.' },
  { name: 'Death Knight', description: 'An undead warrior wielding necrotic powers and plate armor.' },
  { name: 'Defender', description: 'A pure defensive tank focused on drawing enemy attacks.' },
  { name: 'Demon Hunter', description: 'A ranged and melee hybrid dedicated to hunting demonic foes.' },
  { name: 'Destroyer', description: 'A pure damage-focused warrior with heavy weapons.' },
  { name: 'Diviner', description: 'A mage specializing in seeing the future and revealing secrets.' },
  { name: 'Dragoon', description: 'An acrobatic lancer who leaps high to strike enemies with spears.' },
  { name: 'Druid', description: 'A nature magician who shapeshifts into animals and commands plants and wildlife.' },
  { name: 'Duelist', description: 'A light-armored, one-on-one combat specialist.' },
  { name: 'Dwarven Defender', description: 'A stout, immovable tank rooted to defend a spot.' },
  { name: 'Enchanter', description: 'A mage who manipulates minds and controls crowds.' },
  { name: 'Engineer', description: 'A tech-wizard creating automated turrets, gadgets, and bombs.' },
  { name: 'Evoker', description: 'A wizard who specializes in direct-damage spells.' },
  { name: 'Fighter', description: 'The classic, well-rounded master of all melee weapons and armor.' },
  { name: 'Fist Fighter', description: 'An unarmed brawler without the spiritual discipline of a Monk.' },
  { name: 'Frost Mage', description: 'A specialized Black Mage focusing on ice spells and control.' },
  { name: 'Fury', description: 'A rage-filled fighter who deals high damage at the cost of defense.' },
  { name: 'Geomancer', description: 'A mage who casts spells attuned to terrain and natural settings.' },
  { name: 'Gladiator', description: 'An arena-trained fighter focused on showmanship.' },
  { name: 'Guardian', description: 'A highly defensive protector specializing in damage prevention.' },
  { name: 'Gunner', description: 'A marksman specializing in firearms and heavy artillery.' },
  { name: 'Healer', description: 'A class entirely devoted to healing and curing ailments.' },
  { name: 'Herald', description: 'A supportive palladin who inspires allies.' },
  { name: 'Hunter', description: 'A wilderness tracker who sets traps and uses ranged weapons.' },
  { name: 'Illusionist', description: 'A stealthy mage using deceptive spells to misdirect.' },
  { name: 'Infiltrator', description: 'A master of stealth, blending into enemy ranks.' },
  { name: 'Inquisitor', description: 'A righteous zealot who hunts heretics and mages.' },
  { name: 'Invoker', description: 'A divine caster calling on deity power to smite foes.' },
  { name: 'Juggernaut', description: 'An unstoppable tank built to absorb massive punishment.' },
  { name: 'Kensai', description: 'A warrior-monk dedicating life to a single weapon.' },
  { name: 'Knight', description: 'The classic tank, heavily armored and often wielding sword and shield.' },
  { name: 'Lancer', description: 'A mobile spear-wielder relying on reach and agility.' },
  { name: 'Loremaster', description: 'An expert scholar who identifies weaknesses and supports.' },
  { name: 'Machinist', description: 'A hybrid fighter using firearms and clockwork devices.' },
  { name: 'Mage', description: 'The standard arcane spellcaster, versatile but sometimes fragile.' },
  { name: 'Magus', description: 'A hybrid sword-and-spell class blending physical and magical might.' },
  { name: 'Marauder', description: 'A brutal, aggressive melee attacker who may use two-handed axes.' },
  { name: 'Marksman', description: 'A ranged specialist focused on critical hits.' },
  { name: 'Mechanist', description: 'An engineer specializing in constructs and machines.' },
  { name: 'Medic', description: 'A non-magical healer with advanced medical training.' },
  { name: 'Mesmer', description: 'A blue mage of illusions and phantasmal soldiers.' },
  { name: 'Mindflayer', description: "A psionic charmer controlling enemies' minds." },
  { name: 'Monk', description: 'A spiritual, unarmed martial artist who focuses on speed and stunning blows.' },
  { name: 'Mystic', description: 'A psychic or spiritual caster focusing on mental powers.' },
  { name: 'Necromancer', description: 'A dark caster who reforges undead minions and decays foes with death magic.' },
  { name: 'Ninja', description: 'A stealth-based assassin known for agility, poisons, and martial arts.' },
  { name: 'Oracle', description: 'A caster channeling prophecies and divine mysteries.' },
  { name: 'Paladin', description: 'A holy knight in shining armor who wields both sword and healing light.' },
  { name: 'Priest', description: 'A divine healer and buffer, often depicted as a holy servant.' },
  { name: 'Ranger', description: 'A wilderness expert who tracks, traps, and fights with bows or dual blades.' },
  { name: 'Ravager', description: 'A destructive force in battle focusing on area damage.' },
  { name: 'Reaver', description: 'A life-stealing warrior draining health from foes.' },
  { name: 'Red Mage', description: 'A versatile arcane caster blending white and black magic while being competent with a blade.' },
  { name: 'Revenant', description: 'A vengeful undead or channeler of lost legends.' },
  { name: 'Rogue', description: 'The stealthy archetype for picking locks, disarming traps, and attacking from the shadows.' },
  { name: 'Runecaster', description: 'An enchanter inscribing runes to shape reality.' },
  { name: 'Saboteur', description: 'A debuff-focused rogue hindering foes with tools.' },
  { name: 'Sage', description: 'A high-tier caster mixing white and black magic.' },
  { name: 'Samurai', description: 'An honorable eastern warrior balancing martial prowess.' },
  { name: 'Scholar', description: 'A learned tactician who analyzes and supports.' },
  { name: 'Scout', description: 'A reconnaissance class excelling at spotting danger.' },
  { name: 'Seer', description: 'A prophetic caster glimpsing future events.' },
  { name: 'Sentinel', description: 'A pure defensive tank built on survivability.' },
  { name: 'Shadowblade', description: 'A stealthy assassin weaving shadow manipulation.' },
  { name: 'Shadowdancer', description: 'A rogue who moves through shadows magically.' },
  { name: 'Shadowknight', description: 'A plate-wearing anti-paladin wielding dark curses.' },
  { name: 'Shaman', description: 'A tribal caster who communes with spirits and elements.' },
  { name: 'Shifter', description: 'A shapeshifting druid variant focusing on beast forms.' },
  { name: 'Sniper', description: 'A long-range expert dealing massive single-target damage.' },
  { name: 'Soldier', description: 'A generic frontline fighter similar to the Fighter.' },
  { name: 'Sorcerer', description: 'An innate mage drawing power from bloodlines rather than study.' },
  { name: 'Spellblade', description: 'A magical duelist infusing attacks with elements.' },
  { name: 'Spellthief', description: 'A rogue adept at stealing spells and rare items.' },
  { name: 'Striker', description: 'A martial artist focusing on rapid blows.' },
  { name: 'Summoner', description: 'A caster calling forth creatures to fight.' },
  { name: 'Swashbuckler', description: 'A charismatic, agile duelist favoring rapiers.' },
  { name: 'Templar', description: 'A divine defender smiting heretics with righteous fury.' },
  { name: 'Thaumaturge', description: 'A scholar of magical wonders and phenomena.' },
  { name: 'Thief', description: 'The classic scoundrel who steals items and disables traps.' },
  { name: 'Trickster', description: 'A magical illusionist specializing in deceit.' },
  { name: 'Troubadour', description: 'A musical supporter similar to the Bard.' },
  { name: 'Vagabond', description: 'A wandering fighter surviving by versatility.' },
  { name: 'Vindicator', description: 'A zealot delivering brutal, righteous punishment.' },
  { name: 'Warden', description: 'A nature-oriented guardian.' },
  { name: 'Warlock', description: 'An occult magic user.' },
  { name: 'Warmage', description: 'An armored caster focusing purely on battle magic.' },
  { name: 'Warrior', description: 'A pure physical fighter.' },
  { name: 'Weapon Master', description: 'A fighter devoted to mastering one weapon type.' },
  { name: 'White Mage', description: 'The definitive healer using restorative holy magic and buffs.' },
  { name: 'Windwalker', description: 'A monk embracing mobility and air-like strikes.' },
  { name: 'Witch', description: 'A natural spellcaster of dark but primal magic.' },
  { name: 'Witch Doctor', description: 'A tribal debuffer who uses curses and voodoo magic.' },
  { name: 'Wizard', description: 'A studious arcane caster with a vast array of spells for any situation.' },
  { name: 'Zealot', description: 'A fervent religious warrior.' },
  { name: 'Zodiac', description: 'An astrological caster.' },
];
