export interface ProfessionDefinition {
  name: string;
  description: string;
}

export const PROFESSION_CATALOG: ProfessionDefinition[] = [
  { name: 'Alchemist', description: 'Transmutes base metals, brews potions, and seeks the Philosopher’s Stone.' },
  { name: 'Apothecary', description: 'Prepares and sells medicinal herbs, poisons, and simple remedies.' },
  { name: 'Arcane Scribe', description: 'Copies spell scrolls and enchanted texts with magical inks.' },
  { name: 'Armorer', description: 'Crafts metal armor, helmets, and shields.' },
  { name: 'Arrow Smith', description: 'Fletches arrows and bolts, often working alongside bowyers.' },
  { name: 'Astrologer', description: 'Studies celestial bodies to cast horoscopes and predict events.' },
  { name: 'Baker', description: 'Bakes bread, pastries, and other goods in a communal oven.' },
  { name: 'Barber-Surgeon', description: 'Performs bloodletting, tooth pulling, and minor surgeries.' },
  { name: 'Beast Handler', description: 'Trains and cares for war mounts, hunting beasts, or magical creatures.' },
  { name: 'Beekeeper (Apiarist)', description: 'Tends bees, harvests honey and wax for candles and mead.' },
  { name: 'Blacksmith', description: 'Forges iron tools, weapons, horseshoes, and hardware.' },
  { name: 'Bombardier', description: 'Operates and maintains early cannons and gunpowder weapons.' },
  { name: 'Bookbinder', description: 'Sews and binds pages into covers, often decorating with leather or metal.' },
  { name: 'Bowyer', description: 'Crafts longbows, crossbows, and composite bows.' },
  { name: 'Brewster / Brewer', description: 'Produces ale, beer, and mead for taverns and households.' },
  { name: 'Bricklayer', description: 'Lays bricks and tiles for buildings and ovens.' },
  { name: 'Butcher', description: 'Slaughter livestock and prepares meat for sale.' },
  { name: 'Candlemaker (Chandler)', description: 'Makes tallow or beeswax candles for light and rituals.' },
  { name: 'Carpenter', description: 'Works wood for buildings, furniture, and wagon wheels.' },
  { name: 'Cartographer', description: 'Draws maps and nautical charts, sometimes infused with magic.' },
  { name: 'Charcoal Burner', description: 'Produces charcoal for smithies and heating.' },
  { name: 'Chimney Sweep', description: 'Cleans soot from flues and chimneys.' },
  { name: 'Cleric (Religious Order)', description: 'Administers rites, heals the sick, and maintains shrines.' },
  { name: 'Clockmaker', description: 'Builds mechanical clocks, automata, and intricate gears (steampunk edge).' },
  { name: 'Cooper', description: 'Crafts barrels, casks, and buckets from wooden staves.' },
  { name: 'Coppersmith', description: 'Works copper and brass for kettles, stills, and decorative items.' },
  { name: 'Cordwainer', description: 'Makes fine leather shoes and boots.' },
  { name: 'Courier', description: 'Carries messages and small parcels across dangerous routes.' },
  { name: 'Cutler', description: 'Produces knives, daggers, and sword blades.' },
  { name: 'Distiller', description: 'Produces spirits and high-proof alcohol for drinking or alchemical solvents.' },
  { name: 'Dyer', description: 'Colors cloth and leather using natural or magical pigments.' },
  { name: 'Enchanter', description: 'Imbues weapons, armor, and items with magical properties.' },
  { name: 'Engineer (Siege)', description: 'Designs and builds trebuchets, battering rams, and gunpowder cannons.' },
  { name: 'Executioner', description: 'Performs capital punishment and torture as required by law.' },
  { name: 'Farmer', description: 'Cultivates crops and raises livestock for food and raw materials.' },
  { name: 'Farrier', description: 'Trims and shoes horses, also treats hoof ailments.' },
  { name: 'Fletcher', description: 'Specifically fletches arrows (attaches feathers) and fits arrowheads.' },
  { name: 'Forge Priest', description: 'A dwarven or religious smith who blesses weapons during forging.' },
  { name: 'Gaffer (Glassblower)', description: 'Makes glassware, windows, and decorative flasks.' },
  { name: 'Gearsmith', description: 'Builds clockwork mechanisms, cog-driven devices, and prosthetics.' },
  { name: 'Gemcutter', description: 'Cuts and polishes gemstones for jewelry, focuses, or runestones.' },
  { name: 'Gravedigger', description: 'Digs graves and tends cemeteries, often a low-caste but necessary role.' },
  { name: 'Guard / Watchman', description: 'Patrols walls, gates, and streets; enforces local law.' },
  { name: 'Gunsmith', description: 'Forges and repairs early firearms (matchlocks, flintlocks, or steampunk rifles).' },
  { name: 'Harvester', description: 'Collects rare herbs, fungi, or monster parts (steampunk collector).' },
  { name: 'Hatmaker (Milliner)', description: 'Creates hats from felt, straw, or exotic leathers.' },
  { name: 'Healer (Wise Woman / Cunning Folk)', description: 'Uses folk remedies, poultices, and minor charms.' },
  { name: 'Heraldist', description: 'Designs and maintains coats of arms, flags, and noble lineages.' },
  { name: 'Herbalist', description: 'Gathers and identifies wild plants for medicinal or magical use.' },
  { name: 'Illuminator', description: 'Paints illustrations and gold leaf decorations in manuscripts.' },
  { name: 'Innkeeper', description: 'Runs a tavern or inn, providing food, drink, and lodging.' },
  { name: 'Jeweler', description: 'Crafts rings, brooches, and amulets; may work in silver and gold.' },
  { name: 'Lamplighter', description: 'Lights and extinguishes street lamps (steampunk city setting).' },
  { name: 'Lector', description: 'Reads aloud in scriptoriums or for nobles; also a scholar’s assistant.' },
  { name: 'Linen Armorer', description: 'Crafts padded gambesons and arming doublets.' },
  { name: 'Locksmith', description: 'Makes and repairs locks, keys, and simple security mechanisms.' },
  { name: 'Manasmith', description: 'A steampunk/fantasy engineer who forges mana-conducting metal and powers magical machines.' },
  { name: 'Mason', description: 'Cuts and lays stone for castles, cathedrals, and bridges.' },
  { name: 'Miller', description: 'Operates a watermill or windmill to grind grain into flour.' },
  { name: 'Miner', description: 'Extracts ore, coal, or crystal from underground tunnels.' },
  { name: 'Minstrel / Troubadour', description: 'Sings songs, plays lute or harp, tells stories.' },
  { name: 'Monk (Scriptorium)', description: 'Copies religious texts and preserves knowledge.' },
  { name: 'Necroforager', description: 'A fantasy job: harvests reagents from undead or cursed sites (underworld merchant).' },
  { name: 'Ostler', description: 'Cares for horses at an inn or stable; grooms and feeds.' },
  { name: 'Painter', description: 'Paints murals, portraits, and religious icons.' },
  { name: 'Parchment Maker', description: 'Prepares animal skins into writing material.' },
  { name: 'Plowman', description: 'Plows fields, often with draft animals; a specialized farm laborer.' },
  { name: 'Plumber (Pewterer)', description: 'Works with lead and pewter for pipes, cisterns, and utensils.' },
  { name: 'Poisoner', description: 'A dark profession: brews toxins for assassination or pest control.' },
  { name: 'Potter', description: 'Makes clay pots, jugs, and roof tiles on a wheel.' },
  { name: 'Ratter', description: 'Catches rats for pest control; sometimes keeps terriers.' },
  { name: 'Rigger', description: 'Maintains sails and ropes on ships (or airships in steampunk).' },
  { name: 'Ropemaker', description: 'Twists fibers into rope, which is used in countless trades.' },
  { name: 'Runescribe', description: 'Carves magical runes onto weapons, standing stones, or amulets.' },
  { name: 'Saddler', description: 'Makes and repairs saddles, bridles, and harnesses.' },
  { name: 'Sailor', description: 'Crews merchant vessels, warships, or river barges.' },
  { name: 'Sapper', description: 'Digs tunnels and mines for warfare or construction.' },
  { name: 'Scribe', description: 'Writes letters, legal documents, and books by hand.' },
  { name: 'Seamstress / Tailor', description: 'Cuts and sews clothing, cloaks, and banners.' },
  { name: 'Shipwright', description: 'Builds and repairs wooden ships or airships.' },
  { name: 'Siege Medic', description: 'Heals soldiers on the battlefield using bandages, splints, and salves.' },
  { name: 'Skinner (Tanner)', description: 'Tans hides into leather; also flays animals for their pelts.' },
  { name: 'Slater', description: 'Lays roof slates (stone tiles) for castles and churches.' },
  { name: 'Smith (General)', description: 'Works iron and steel for all manner of tools and weapons.' },
  { name: 'Soaper', description: 'Makes soap from fat and lye, also produces glycerin.' },
  { name: 'Soul Binder', description: 'Fantasy job: anchors ghosts or souls into constructs or golems.' },
  { name: 'Spellwright', description: 'A magic user who composes new spells and magical formulae.' },
  { name: 'Spicer', description: 'Sells exotic spices, sugar, and rare herbs (high-value trade).' },
  { name: 'Stonecarver', description: 'Carves gargoyles, statues, and reliefs from stone.' },
  { name: 'Stonemason', description: 'Cuts and builds with natural stone (more structural than carver).' },
  { name: 'Steward', description: 'Manages a noble household’s finances, staff, and estate.' },
  { name: 'Tanner', description: 'Converts animal hides into durable leather using tanning baths.' },
  { name: 'Thaumaturge', description: 'Performs public miracles and lesser magic (entertainment or faith).' },
  { name: 'Thatcher', description: 'Thatch roofs with straw or reeds.' },
  { name: 'Tinker', description: 'Repairs pots, kettles, and metal household goods; often itinerant.' },
  { name: 'Tracker (Hunter)', description: 'Follows tracks, hunts game, and protects livestock from predators.' },
  { name: 'Vintner', description: 'Grows grapes and produces wine.' },
  { name: 'Wainwright', description: 'Builds and repairs wagons and carts.' },
  { name: 'Wand Maker', description: 'Selects wood and cores to craft magical foci for wizards.' },
  { name: 'Weaponmaster', description: 'A guilded expert who teaches swordsmanship, polearms, or archery.' },
];
