export interface RaceDefinition {
  name: string;
  description: string;
}

export const RACE_CATALOG: RaceDefinition[] = [
  { name: 'Aarakocra', description: 'intelligent bird-like humanoids, known for their ability to fly.' },
  { name: 'Aasimar', description: 'human-like beings with a touch of celestial or divine power in their bloodline.' },
  { name: 'Al Bhed', description: 'a race of green-eyed, non-magical humans from the Final Fantasy series.' },
  { name: 'Anime Elves', description: 'a common portrayal of elves in anime and manga, often with distinct physical features and magical abilities.' },
  { name: 'Argonian', description: 'a race of reptilian humanoids from The Elder Scrolls series, known for their resistance to disease and ability to breathe water.' },
  { name: 'Asura', description: 'a magically gifted, diminutive humanoid race with genius-level intellects from the Guild Wars universe.' },
  { name: 'Auriel (High Elf)', description: 'a tall, fair-skinned, and magically gifted elven subrace.' },
  { name: 'Balrog', description: "a powerful, demonic being of fire and shadow from J.R.R. Tolkien's Middle-earth legendarium." },
  { name: 'Bangaa', description: 'a race of reptilian humanoids from the Final Fantasy series, known for their strength and long lifespans.' },
  { name: 'Beastkin', description: 'a broad term for races that physically blend human and animal traits.' },
  { name: 'Beastman', description: 'a general term for races that combine human and animal features, also known as "beastfolk" or "demihumans".' },
  { name: 'Blood Elf', description: 'a race of elves from the Warcraft universe, cursed by magical addiction, known for their magical prowess.' },
  { name: 'Bosmer (Wood Elf)', description: 'a race of elves native to the forests of Valenwood in The Elder Scrolls, known for their archery skills.' },
  { name: 'Breton', description: 'a race of humans from The Elder Scrolls with a natural affinity for magic due to their mixed Elven and Human ancestry.' },
  { name: 'Bretonnian', description: 'a human race from the Warhammer Fantasy setting, based on Arthurian legend.' },
  { name: 'Broken', description: 'a devolved, mutated sub-race of the Draenei from the Warcraft universe, corrupted by fel energies.' },
  { name: 'Bugbear', description: 'a large, often hairy, and powerful race of goblinoids, known for their strength.' },
  { name: 'Cabal', description: 'a militaristic, turtle-like alien race from the Destiny video game series.' },
  { name: 'Cathay', description: 'a human nation in Warhammer Fantasy, inspired by ancient China.' },
  { name: 'Centaur', description: 'a race with the upper body of a human and the lower body of a horse.' },
  { name: 'Changeling', description: 'a race of shapeshifters that can alter their appearance at will.' },
  { name: 'Charr', description: 'a large, bestial, feline race from the Guild Wars universe, known for their industrial nature and military culture.' },
  { name: 'Chromatic Dragon', description: 'a category of dragons associated with evil alignments and elemental breath weapons, such as red, blue, and green dragons.' },
  { name: 'Darkspawn', description: 'a corrupted, monstrous race that serves as the primary antagonist force in the Dragon Age series.' },
  { name: 'Dark Elf (Drow)', description: 'a subterranean race of elves with dark skin, often associated with evil and chaos, also known as Drow.' },
  { name: 'Dead (Undead)', description: 'corpses reanimated through necromantic magic, ranging from mindless zombies to intelligent liches and vampires.' },
  { name: 'Dragon', description: 'a mythical, sapient race of powerful, fire-breathing, winged reptiles.' },
  { name: 'Dragonborn', description: 'a race of proud, dragon-like humanoids, capable of using a breath weapon.' },
  { name: 'Draenei', description: 'an ancient race of horned humanoids from the Warcraft universe, exiled from their homeworld.' },
  { name: 'Drakanite', description: 'a draconic-themed humanoid race, often portrayed as the third most numerous race in fantasy world-building.' },
  { name: 'Dwarf / Dvergar', description: 'a short, stout race known for their skill in mining, smithing, and combat, often living in mountainous regions.' },
  { name: 'Eladrin', description: 'a race of powerful fey elves, capable of shifting between seasons and planes of existence in D&D.' },
  { name: 'Elemental', description: 'a being composed of and embodying a fundamental element of nature, such as fire, water, earth, or air.' },
  { name: 'Elf', description: 'a tall, slender, long-lived humanoid race typically portrayed as graceful and highly intelligent, with a deep connection to nature or magic.' },
  { name: 'Ent', description: "also known as Onodrim, a race of ancient, sentient, tree-like beings in J.R.R. Tolkien's Middle-earth." },
  { name: 'Fairy', description: 'a small, winged humanoid race often depicted with magical powers, also referred to as a Fae.' },
  { name: 'Falmer (Snow Elf)', description: 'a race of blind, twisted elves dwelling in the darkest depths of Skyrim in The Elder Scrolls.' },
  { name: 'Firbolg', description: 'a quiet, reclusive race of giant-kin with a strong connection to nature.' },
  { name: 'Giant', description: 'a race of immense, humanoid beings, varying greatly in size, intelligence, and temperament.' },
  { name: 'Githyanki', description: 'an astral race of gaunt, yellow-skinned humanoids, descended from ancient human slaves of illithids.' },
  { name: 'Githzerai', description: 'a disciplined race of psionic humanoids, originating as slaves of the illithids, now dwelling in limbo.' },
  { name: 'Gnome', description: 'a short, inventive race often known for their tinkering skills, magical aptitude, and fascination with gems.' },
  { name: 'Goblin / Goblinoid', description: 'a small, green-skinned humanoid race often portrayed as greedy and mischievous, known for their numerical strength.' },
  { name: 'Goliath', description: 'a tall, strong, and nomadic race marked by bony growths, adapted to high-altitude living.' },
  { name: 'Grell', description: 'a floating, carnivorous, tentacled race from Dungeons & Dragons known for their psionic abilities and beak-like mouths.' },
  { name: 'Gremlin', description: 'a mischievous fairy creature from European folklore, known for causing malfunctions in mechanical devices.' },
  { name: 'Griffon', description: 'legendary creatures with the body of a lion and the head and wings of an eagle.' },
  { name: 'Guado', description: 'an arboreal humanoid race in the Final Fantasy X universe, known for having long fingers and acidic fluids.' },
  { name: 'Half-Elf', description: 'a hybrid race born of human and elf parents, often bridging the gap between the two cultures.' },
  { name: 'Half-Orc', description: 'a hybrid race born of humans and orcs, often depicted as strong but shunned by both societies.' },
  { name: 'Halfling (Hobbit)', description: 'a small, gentle, and quiet race known for their love of peace, food, and agriculture, also known as Hobbits.' },
  { name: 'Harpy', description: "a winged humanoid creature from Greek mythology, often depicted with a woman's head and torso and a bird's lower half." },
  { name: 'High Elf', description: 'a noble, magically-gifted, fair-skinned elven subrace, also known as Altmer in The Elder Scrolls.' },
  { name: 'Hobgoblin', description: 'a larger, more militant race of goblinoids, known for their discipline and organization in tribal societies.' },
  { name: 'Homunculus', description: 'a small, artificially-created humanoid in alchemy and fantasy, often serving as a familiar or assistant.' },
  { name: 'Human', description: 'the most common and versatile race in fantasy, known for their ambition, adaptability, and relatively short lifespans.' },
  { name: 'Hume', description: 'the term for a standard human in the Final Fantasy XI universe, known for their balanced abilities and versatility.' },
  { name: 'Imperial', description: 'a race of humans from the province of Cyrodiil in The Elder Scrolls, known for their discipline, commerce, and diplomacy.' },
  { name: 'Kenku', description: 'a raven-like avian humanoid race, cursed with the loss of their wings and their original voice.' },
  { name: 'Khajiit', description: 'a feline humanoid race from the province of Elsweyr in The Elder Scrolls, known for their agility and lunar variations.' },
  { name: 'Klingon', description: 'a fictional warrior race in the Star Trek franchise, known for their honor, strength, and distinct forehead ridges.' },
  { name: 'Kobito', description: 'a short, beetle-like race of craftsmen from Japanese fantasy, known for their skill in creating living tools.' },
  { name: 'Kobold', description: 'a small, dragon-like, humanoid race, often considered cowardly but cunning, known for their skill in traps and mining.' },
  { name: 'Lamassu', description: "a creature with a human head, the body of a bull or lion, and the wings of an eagle, originating from Assyrian mythology." },
  { name: 'Lamia', description: "a creature from Greek mythology, often depicted as a half-woman, half-serpent monster that preys on children and young men." },
  { name: 'Lich', description: 'a powerful, malevolent undead wizard who has achieved immortality through necromancy and a phylactery.' },
  { name: 'Lizardman / Lizardfolk', description: 'a race of reptilian humanoids, often living in swamps or jungles, known for their primal strength and connection to nature.' },
  { name: 'Loxodon', description: 'a race of elephantine humanoids known for their strong moral compass, wisdom, and impressive memory.' },
  { name: 'Merfolk', description: 'a race of aquatic humanoids, typically depicted with the upper body of a human and the lower body of a fish (e.g., mermaids and mermen).' },
  { name: 'Mimic', description: 'a monstrous race of shapeshifters capable of transforming into inanimate objects, such as treasure chests, to ambush prey.' },
  { name: 'Minotaur', description: 'a huge, muscular race with the head of a bull and the body of a human, often depicted as strong and intimidating.' },
  { name: 'Modron', description: 'a race of mechanical, geometric beings from the plane of Mechanus in Dungeons & Dragons, governed by strict law and order.' },
  { name: 'Moogle', description: 'a small, furry, winged creature with a distinctive red pom-pom antenna, serving as a recurring mascot in the Final Fantasy series.' },
  { name: 'Mystic', description: 'a race of humans with a hereditary ability to absorb and manipulate universal energy in the Fabletop universe.' },
  { name: 'Naga', description: "a race of serpentine creatures from Hindu mythology and fantasy worlds, often depicted with a human-like upper body and a snake's tail." },
  { name: 'Night Elf', description: 'a nocturnal, purple-skinned elven race from the Warcraft universe, blessed with immortality and a deep connection to nature.' },
  { name: 'Nord', description: 'a tall, fair-haired race of humans from the province of Skyrim in The Elder Scrolls, known for their resistance to cold and warrior culture.' },
  { name: 'Norn', description: 'a tall, shapeshifting, giant-like humanoid race from the Guild Wars universe, drawing power from animal spirits.' },
  { name: 'Nymph', description: 'a female nature spirit from Greek mythology, often associated with a specific location or landform, such as trees, springs, or mountains.' },
  { name: 'Ogre', description: 'a large, brutish humanoid race, often depicted as unintelligent but immensely strong and voracious.' },
  { name: 'Orc', description: 'a savage, warlike humanoid race typically depicted with greenish skin, prominent tusks, and immense physical strength.' },
  { name: 'Orsimer (Orc)', description: 'the orc race in The Elder Scrolls, who were once elves but were transformed into their bestial form by a Daedric Prince.' },
  { name: 'Pegasus', description: 'a divine winged horse from Greek mythology, often depicted as pure white and capable of flight.' },
  { name: 'Redguard', description: 'a race of tall, dark-skinned humans from the province of Hammerfell in The Elder Scrolls, known for their sword-singing and physical prowess.' },
  { name: 'Riolu', description: 'a small, blue, canine-like creature from the Pokemon series, capable of sensing emotions through aura.' },
  { name: 'Satyr', description: 'a race of nature-spirits from Greek mythology, depicted as male humanoids with the legs, tail, and horns of a goat.' },
  { name: 'Savage', description: 'a broad term encompassing primitive or tribal-themed races like orcs, beastmen, or barbaric humans, often characterized by their raw strength and martial prowess.' },
  { name: 'Scourge', description: 'the army of the Undead in the Warcraft universe, a parasitic race threatening all of Azeroth.' },
  { name: 'Shadar-kai', description: 'a gaunt, pale race of elves from the Shadowfell in Dungeons & Dragons, known for their connection to shadow and melancholy.' },
  { name: 'Shifter', description: 'a race of lycanthrope-descended humanoids, capable of temporarily manifesting bestial traits in Dungeons & Dragons.' },
  { name: 'Skaven', description: 'a malevolent, technologically advanced race of ratmen from the Warhammer Fantasy universe, known for their scheming and immense numbers.' },
  { name: 'Slime', description: 'a versatile, amorphous race of gelatinous creatures, ranging from simple monsters to intelligent beings, capable of absorbing various traits.' },
  { name: 'Sphinx', description: 'a mythical creature with the body of a lion and the head of a human, often depicted as a guardian of treasures and riddles.' },
  { name: 'Stout', description: 'a fantasy archetype that encompasses short, sturdy races like dwarves, gnomes, and sometimes hobbits, known for their resilience and craftsmanship.' },
  { name: 'Sylvan', description: 'a term generally used for a race of forest-dwelling elf-like fey or a specific type of plant-person like the Sylvari of Guild Wars.' },
  { name: 'Tabaxi', description: 'a curious, feline humanoid race, known for their love of collecting stories and treasures from their travels.' },
  { name: "Tanar'ri", description: 'the primary race of chaotic evil demons inhabiting the Abyss in Dungeons & Dragons planar cosmology.' },
  { name: 'Tarutaru', description: 'a diminutive, child-like race from Final Fantasy XI, notable for their immense magical potential and short stature.' },
  { name: 'Tiefling', description: 'a human-like race with fiendish ancestry, often possessing horns, a tail, and unusual skin colors, such as red or purple.' },
  { name: 'Treant', description: 'a sentient, humanoid tree, serving as ancient guardians of the forest and powerful allies of druids.' },
  { name: 'Triton', description: 'an aquatic humanoid race, adapted to ocean life, often serving as guardians of the sea floor and ambassadors of the deep.' },
  { name: 'Troglodyte', description: 'a primitive, subterranean race of reptilian humanoids known for their foul stench and cruelty, often found in caves.' },
  { name: 'Troll', description: 'a large, brutish humanoid race, known for their incredible regenerative capabilities and vulnerability to fire.' },
  { name: "Twi'lek", description: 'a humanoid alien species from the Star Wars universe, distinguished by their two long, prehensile appendages (lekku) growing from their skulls.' },
  { name: 'Viera', description: 'a proud, reclusive rabbit-like humanoid race from the Final Fantasy XII and Tactics Advance games, known for their hearing and agility.' },
  { name: 'Wight', description: 'a corporeal undead creature, more powerful than a skeleton or zombie, known for draining the life energy from its victims.' },
  { name: 'Werewolf', description: 'a humanoid race capable of shapeshifting into a wolf-like form under the light of the full moon, also known as Lycanthropes.' },
  { name: 'Worgen', description: 'a cursed race of feral werewolves from the Warcraft universe, who have learn to maintain their sanity and fight for the Alliance.' },
  { name: 'Yuan-ti', description: 'a decadent, reptilian race of snake-like humanoids, dominated by purebloods who can pass as human in Dungeons & Dragons.' },
  { name: 'Yugoloth', description: 'a race of neutral evil fiends, acting as mercenaries and manipulators in the great planar conflicts of Dungeons & Dragons.' },
  { name: 'Zerg', description: 'a terrifying, insectoid alien race from the StarCraft universe, driven by an overwhelming urge to consume and assimilate all organic life.' },
];
