// ─── Library Imports ───────────────────────────────────────────────
// React hooks we use throughout this component:
//   useEffect   – run code when the component loads or when data changes
//   useMemo     – cache expensive calculations so they don't re-run every render
//   useRef      – hold a reference to a DOM element (the dialogue scroll box)
//   useState    – store a value that can change over time (triggers a re-render)
import { useEffect, useMemo, useRef, useState } from 'react';
// useNostr gives us a `nostr` client object we use to read/write Nostr events.
import { useNostr } from '@nostrify/react';
// useNavigate lets us change the browser URL (e.g. go back to the title screen).
import { useNavigate } from 'react-router-dom';
// useQuery handles async data-fetching for us: loading, caching, and re-fetching.
import { useQuery } from '@tanstack/react-query';
// TypeScript type for a Nostr event object (has pubkey, kind, tags, content, etc.).
import type { NostrEvent } from '@nostrify/nostrify';
// ─── Quest Engine Imports ─────────────────────────────────────────
// These are pure functions (no side effects) that manage quest logic.
// Think of engine.ts as the "rules of the game" – this file just calls them.
import {
  applyChoice,            // Apply a player's choice to the quest state
  createInitialQuestState, // Return a brand-new blank quest state
  getCharacterLevel,       // Derive the character's overall level from XP
  getLevelFromXp,          // Convert a raw XP number into a level number
  getCompletedQuestIds,    // List of quest IDs the player has finished
  getCurrentStep,          // Get the current step object for the active quest
  getQuestContext,         // Build a context object (location, flags, completed quests)
  getVisibleQuests,        // Filter quests to only those available to the player
  interpolateStepText,     // Replace {playerName} placeholders in quest dialogue
  normalizeQuestState,     // Fill in any missing fields on a partially-loaded state
  startQuest,              // Mark a quest as the active quest
  submitPlayerName,        // Validate and save the player's chosen name
} from '@/components/rpg/quests/engine';
// allQuests = the array of every quest definition in the game.
// questById = a lookup table so you can do questById['quest-001-origin'] quickly.
import { allQuests, questById } from '@/components/rpg/quests/registry';
// ─── Nostr Save/Load Helpers ─────────────────────────────────────
// These read/write game data to the Nostr network so your progress persists
// across devices.  If Nostr is unreachable, the game falls back to localStorage.
import {
  fetchOrCreateCharacterStartTimestamp, // Get (or create) the timestamp of your first login
  fetchQuestStateSnapshot,              // Load your saved quest progress from Nostr
  publishQuestStateSnapshot,            // Save your quest progress to Nostr
} from '@/components/rpg/gameProfile';
// useCurrentUser returns the currently logged-in Nostr user (or null if not logged in).
import { useCurrentUser } from '@/hooks/useCurrentUser';
// useLoginActions gives us a logout() function.
import { useLoginActions } from '@/hooks/useLoginActions';

// ═══════════════════════════════════════════════════════════════════
//  MOCK / PLACEHOLDER DATA
//  These are temporary stand-ins.  Eventually they'll be replaced
//  with real data pulled from Nostr or generated by the game engine.
// ═══════════════════════════════════════════════════════════════════

// Fake "world signals" shown in the Social tab to hint at lore.
const mockSignals = [
  'Ravenhall gate opens at first bell.',
  'Archivist seeks one bearer of unfinished oaths.',
  'Floodplain caravan expects tribute before moonrise.',
];

// Fake activity feed entries shown in the Social tab.
const socialFeed = [
  'Mira reached level 9 in tracking near the Floodplain Trail.',
  'Thorn unlocked a new skill: Iron Parry.',
  'Lysa discovered the Silent Archive beneath the old chapel.',
  'Corvin earned 24 copper from market contracts.',
  'Nessa defeated a wolf pack and gained 2 pelts.',
  'Eldric completed quest: Ash Bell on the Eastern Stair.',
];

// Fake chat messages shown in the Social tab chat box.
const socialChatMessages = [
  'Mira: Anyone heading to the old well tonight?',
  'Thorn: I can join after market reset.',
  'You: I will scout the orchard path first.',
];

// The starting event log (the little bullet-list beneath the dialogue window).
const mockEventLog = [
  'You found yourself in a forest.',
];

// This message is shown to the player right after they choose their name.
// It explains the core game concept: autonomous character, daily pacing, quests.
const INTRO_DEV_MESSAGE = `Welcome to No Stranger Game! Your character is autonomous! He will act according to his own needs and desires. The primary means of progressing the game is by completing quests. Every choice has a permanent and irrevocable impact on the trajectory of your character, tread CAREFULLY! The game is designed to take about three minutes of your time each day. Be patient... it may seem like nothing is happening... but the game is MASSIVE and changes take place over Days, not seconds. For now your character will explore the forest around him, seeking food and shelter. Soon he will discover a village, which will unlock the next part of the Main Quest. The forest is very large, and your character may discover other locales before the village, and it could take longer than you are anticipating. I recommend you take a few minutes to look around the game, and then check your character's progress tomorrow.

If you have any questions please reach out to me on Nostr.

Thank you for playing!`;

// ═══════════════════════════════════════════════════════════════════
//  GAME WORLD CONSTANTS
// ═══════════════════════════════════════════════════════════════════

// The player's current location.  Hardcoded for now – will eventually be
// driven by game state once more locations (Town, Ruins, etc.) are added.
const currentLocation = 'Forest';

// Actions available at each location.  Shown as clickable buttons on the
// Play tab.  The key is the location name, the value is a list of actions.
const locationActions: Record<string, string[]> = {
  Town: ['Visit the tavern', 'Visit the market'],
  Forest: ['Interact with the old well', 'Visit the abandoned cabin'],
};

// Starting character stats.  All begin at 1 (blank slate). Quest choices
// will modify these over time via the modifiers system.
const characterStats = [
  ['Strength', '1'],
  ['Dexterity', '1'],
  ['Constitution', '1'],
  ['Intelligence', '1'],
  ['Wisdom', '1'],
  ['Charisma', '1'],
];

// These arrays start empty.  As the player progresses through quests and
// the game world, items will be added here (e.g. "Hiking 3", "Cautious").
const characterSkills: string[] = [];
const characterTraits: string[] = [];
const characterRelationships: string[] = [];
const characterAffinities: string[] = [];
const characterAfflictions: string[] = [];
const characterBlessings: string[] = [];
const characterCurses: string[] = [];

// ═══════════════════════════════════════════════════════════════════
//  TYPES & CONFIGURATION
// ═══════════════════════════════════════════════════════════════════

// The five tabs at the bottom of the phone-frame UI.
type MobileTab = 'character' | 'quests' | 'play' | 'map' | 'social';
// localStorage keys – these strings are the "names" under which we save data
// in the browser.  Each logged-in user gets their own key by appending their pubkey.
const QUEST_STATE_STORAGE_KEY = 'nsg:facsimile-quest-state';
const CHARACTER_START_TS_STORAGE_KEY = 'nsg:character-start-timestamp';
const DEV_DAY_OFFSET_STORAGE_KEY = 'nsg:dev-day-offset-ms';
// One day in milliseconds (24 hours * 60 minutes * 60 seconds * 1000 ms).
const DAY_IN_MS = 24 * 60 * 60 * 1000;
// How much XP the character earns passively each day (1 XP per minute = 1440).
const DAILY_XP = 1440;
// Auto-generated avatar image from DiceBear (a free avatar API).
const NPC_AVATAR_URL = 'https://api.dicebear.com/8.x/adventurer/svg?seed=Elira';
// The player needs at least this many points in a class modifier (e.g.
// WarriorClass >= 5) before they stop being a "Stranger" and become that class.
const CLASS_UNLOCK_POINTS = 5;
// Nostr event "kinds" are just numbers that tell relays what type of data this is.
// 10031 = our custom "character start timestamp" event (see NIP.md).
const CHARACTER_START_KIND = 10031;
// The "d" tag value that identifies our character-start event on Nostr.
const CHARACTER_START_D_TAG = 'character-start';
// Kind 3 is a standard Nostr event: a user's follow list (who they follow).
const FOLLOW_LIST_KIND = 3;

// ─── Character Class Logic ────────────────────────────────────────
// Checks the player's accumulated modifiers (earned from quest choices) to
// determine their class.  If no class has enough points, they're a "Stranger".
// Example: choosing "Strike it!" in Quest 002 gives WarriorClass +1.
const getCharacterClass = (modifiers: Record<string, number>): 'Warrior' | 'Rogue' | 'Mage' | 'Stranger' => {
  const classScores: Array<{ name: 'Warrior' | 'Rogue' | 'Mage'; score: number }> = [
    { name: 'Warrior', score: modifiers.WarriorClass ?? 0 },
    { name: 'Rogue', score: modifiers.RogueClass ?? 0 },
    { name: 'Mage', score: modifiers.MageClass ?? 0 },
  ];

  const unlocked = classScores.filter((entry) => entry.score >= CLASS_UNLOCK_POINTS);
  if (unlocked.length === 0) return 'Stranger';
  return unlocked.sort((a, b) => b.score - a.score)[0].name;
};

// ═══════════════════════════════════════════════════════════════════
//  MAIN COMPONENT
//  This is the React component that renders the entire game interface.
//  Everything below lives inside this one function.  React calls it
//  every time state changes, and it returns the JSX (HTML-like code)
//  that gets painted on screen.
// ═══════════════════════════════════════════════════════════════════
export function RPGInterface() {
  // ─── Hooks: get shared services ───────────────────────────────────
  const { nostr } = useNostr();        // Nostr client for reading/writing events
  const { user } = useCurrentUser();    // The logged-in user (null if not logged in)
  const { logout } = useLoginActions();  // Function to log out
  const navigate = useNavigate();        // Function to change the URL/page
  // ─── Component State ─────────────────────────────────────────────
  // Each useState call creates a piece of data that React tracks.
  // When you call the "set" function (e.g. setActiveTab), React re-renders
  // the component with the new value.

  // Which bottom-nav tab is selected (defaults to 'play').
  const [activeTab, setActiveTab] = useState<MobileTab>('play');
  // Which quest is expanded (open) in the Quests tab.  null = none.
  const [expandedQuestId, setExpandedQuestId] = useState<string | null>(null);
  // The big object that holds ALL quest progress, modifiers, flags, dialogue, etc.
  // This is the "save file" of the game.  See quests/types.ts for its shape.
  const [questState, setQuestState] = useState(createInitialQuestState);
  // The text the player types into the "name your character" input box.
  const [nameInput, setNameInput] = useState('');
  // Validation error message for the name input (e.g. "Name too short").
  const [nameInputError, setNameInputError] = useState<string | null>(null);
  // The bullet-point event log shown below the dialogue panel on the Play tab.
  const [eventLog, setEventLog] = useState<string[]>(mockEventLog);
  // "Hydrated" means we've finished loading saved data.  We don't save
  // anything back until this is true, to avoid overwriting good data with
  // a blank initial state.
  const [isQuestStateHydrated, setIsQuestStateHydrated] = useState(false);
  // The millisecond timestamp of when this character was first created.
  // Used to calculate the "Day N" counter in the header.
  const [characterStartTimestamp, setCharacterStartTimestamp] = useState<number | null>(null);
  // Dev tool: lets you fast-forward time by adding milliseconds.
  // The "24hr" button in the header adds one day here.
  const [devDayOffsetMs, setDevDayOffsetMs] = useState(0);
  // A ref to the dialogue scroll container so we can auto-scroll to the bottom.
  const dialogueScrollRef = useRef<HTMLDivElement | null>(null);
  // Tracks how many quests were completed last render, so we can detect when
  // a NEW quest is completed and trigger a save to Nostr.
  const completedQuestCountRef = useRef(0);

  // Build a per-user localStorage key so different accounts don't share saves.
  const questStateStorageKey = user ? `${QUEST_STATE_STORAGE_KEY}:${user.pubkey}` : QUEST_STATE_STORAGE_KEY;

  // ─── Social Presence Query ────────────────────────────────────────
  // This asks Nostr: "How many people are playing this game?" and
  // "How many of them are mutual follows with me?" (Kindred Spirits).
  // useQuery handles caching so we don't spam relays on every render.
  const socialQuery = useQuery({
    queryKey: ['rpg-social-presence', user?.pubkey ?? 'anonymous'],
    queryFn: async () => {
      // Step 1: Find all character-start events tagged with our game.
      // Each event represents one player who has started the game.
      const loginEvents = await nostr.query([
        {
          kinds: [CHARACTER_START_KIND],
          '#d': [CHARACTER_START_D_TAG],
          '#t': ['no-stranger-game'],
          limit: 200,
        },
      ]);

      // Collect unique player public keys (deduplicate with a Set).
      const playerPubkeys = Array.from(new Set(loginEvents.map((event) => event.pubkey)));
      if (!user?.pubkey || playerPubkeys.length === 0) {
        return {
          totalPlayers: playerPubkeys.length,
          kindredSpirits: 0,
        };
      }

      // Step 2: Fetch everyone's follow lists so we can check mutual follows.
      const contactListEvents = await nostr.query([
        {
          kinds: [FOLLOW_LIST_KIND],
          authors: Array.from(new Set([user.pubkey, ...playerPubkeys])),
          limit: Math.max(20, playerPubkeys.length + 5),
        },
      ]);

      // A user can publish multiple follow-list events over time.
      // We only care about the most recent one per user.
      const latestByAuthor = new Map<string, NostrEvent>();
      contactListEvents.forEach((event) => {
        const existing = latestByAuthor.get(event.pubkey);
        if (!existing || event.created_at > existing.created_at) {
          latestByAuthor.set(event.pubkey, event);
        }
      });

      // Helper: given a follow-list event, return the set of pubkeys they follow.
      // Follow lists use "p" tags – each ["p", "<pubkey>"] is one follow.
      const extractFollowSet = (event: NostrEvent | undefined): Set<string> => {
        if (!event) return new Set();
        return new Set(
          event.tags
            .filter(([name, value]) => name === 'p' && Boolean(value))
            .map(([, value]) => value)
        );
      };

      // Step 3: Count "Kindred Spirits" = other players where BOTH of you
      // follow each other (mutual follows).
      const myFollows = extractFollowSet(latestByAuthor.get(user.pubkey));
      const kindredSpirits = playerPubkeys.filter((pubkey) => {
        if (pubkey === user.pubkey) return false;
        if (!myFollows.has(pubkey)) return false;
        const theirFollows = extractFollowSet(latestByAuthor.get(pubkey));
        return theirFollows.has(user.pubkey);
      }).length;

      return {
        totalPlayers: playerPubkeys.length,
        kindredSpirits,
      };
    },
    staleTime: 60_000, // Cache results for 60 seconds before refetching.
  });
  // Fall back to zeros if the query hasn't loaded yet.
  const socialStats = socialQuery.data ?? {
    totalPlayers: 0,
    kindredSpirits: 0,
  };

  // ─── useEffect #1: Load saved quest state on login ───────────────
  // When the component mounts (or when the user changes), try to load the
  // player's saved quest progress.  Priority order:
  //   1. Nostr (cloud save)  →  most portable, works across devices
  //   2. localStorage (browser save)  →  fallback if Nostr fails
  //   3. Brand-new blank state  →  first-time player
  useEffect(() => {
    let cancelled = false; // Prevents setting state if the component unmounts mid-load.
    setIsQuestStateHydrated(false);

    const loadQuestState = async () => {
      if (user) {
        try {
          const snapshot = await fetchQuestStateSnapshot(nostr, user.pubkey);
          if (!cancelled && snapshot?.state) {
            setQuestState(normalizeQuestState(snapshot.state));
            setIsQuestStateHydrated(true);
            return;
          }
        } catch (error) {
          console.warn('Failed to load quest checkpoint from Nostr, using local fallback.', error);
        }
      }

      try {
        const raw = localStorage.getItem(questStateStorageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          if (parsed && typeof parsed === 'object') {
            if (!cancelled) {
              setQuestState(normalizeQuestState(parsed as Partial<typeof questState>));
              setIsQuestStateHydrated(true);
            }
            return;
          }
        }
      } catch {
        setQuestState(createInitialQuestState());
      }

      if (!cancelled) {
        setQuestState(createInitialQuestState());
        setIsQuestStateHydrated(true);
      }
    };

    void loadQuestState();

    return () => {
      cancelled = true;
    };
  }, [nostr, questStateStorageKey, user]);

  // ─── useEffect #2: Auto-save quest state to localStorage ─────────
  // Every time questState changes (and we've finished loading), write it
  // to localStorage so it's saved even if the player closes the tab.
  useEffect(() => {
    if (!isQuestStateHydrated) return;
    localStorage.setItem(questStateStorageKey, JSON.stringify(questState));
  }, [isQuestStateHydrated, questState, questStateStorageKey]);

  // ─── useEffect #3 & #4: Persist the dev day-offset ────────────────
  // The dev day-offset is how many extra milliseconds to add to "now" for
  // testing.  We save it to localStorage so it survives page refreshes.
  useEffect(() => {
    const raw = localStorage.getItem(DEV_DAY_OFFSET_STORAGE_KEY);
    if (!raw) return;
    const parsed = Number(raw);
    if (!Number.isNaN(parsed)) {
      setDevDayOffsetMs(parsed);
    }
  }, []);  // Empty array = run once when the component first mounts.

  useEffect(() => {
    localStorage.setItem(DEV_DAY_OFFSET_STORAGE_KEY, String(devDayOffsetMs));
  }, [devDayOffsetMs]);  // Runs whenever devDayOffsetMs changes.

  // ─── useEffect #5: Load or create the character start timestamp ───
  // This timestamp records when the player first created their character.
  // It's used to calculate which "Day" they're on (Day 1, Day 2, etc.).
  // Same priority as quest state: Nostr first, then localStorage, then now().
  useEffect(() => {
    let cancelled = false;

    const loadStartTimestamp = async () => {
      try {
        if (user) {
          // Try to read (or create) the start timestamp on Nostr.
          const startTimestamp = await fetchOrCreateCharacterStartTimestamp(nostr, user.pubkey, user.signer);
          if (!cancelled) {
            setCharacterStartTimestamp(startTimestamp);
            localStorage.setItem(CHARACTER_START_TS_STORAGE_KEY, String(startTimestamp));
          }
          return;
        }
      } catch (error) {
        console.warn('Failed to load Nostr start timestamp, using local fallback.', error);
      }

      const localRaw = localStorage.getItem(CHARACTER_START_TS_STORAGE_KEY);
      if (localRaw) {
        const parsed = Number(localRaw);
        if (!Number.isNaN(parsed)) {
          if (!cancelled) setCharacterStartTimestamp(parsed);
          return;
        }
      }

      const fallback = Date.now();
      localStorage.setItem(CHARACTER_START_TS_STORAGE_KEY, String(fallback));
      if (!cancelled) setCharacterStartTimestamp(fallback);
    };

    void loadStartTimestamp();

    return () => {
      cancelled = true;
    };
  }, [nostr, user]);

  // ─── useEffect #6: Auto-scroll dialogue to the bottom ─────────────
  // When new lines are added to the dialogue or the player switches to the
  // Play tab, smoothly scroll the dialogue box to show the newest text.
  useEffect(() => {
    const container = dialogueScrollRef.current;
    if (!container) return;
    if (typeof container.scrollTo === 'function') {
      container.scrollTo({ top: container.scrollHeight, behavior: 'smooth' });
      return;
    }
    container.scrollTop = container.scrollHeight;
  }, [questState.dialogueLog, activeTab]);

  // ─── Derived / Computed Values ───────────────────────────────────
  // useMemo caches the result of a calculation.  It only recalculates when
  // the values in the [dependency array] change.  This avoids doing expensive
  // work on every single render.

  // List of quest IDs the player has finished.
  const completedQuestIds = useMemo(() => getCompletedQuestIds(questState), [questState]);
  // Build a "context" object the quest engine uses to decide which quests are available.
  const questContext = useMemo(
    () => getQuestContext(questState, currentLocation),
    [questState]
  );
  // Filter the full quest list to only those the player can see right now.
  const visibleQuests = useMemo(
    () => getVisibleQuests(allQuests, questContext),
    [questContext]
  );
  // The quest the player is currently doing (or null if between quests).
  const activeQuest = questState.activeQuestId ? questById[questState.activeQuestId] : null;
  // The specific step within the active quest (the current dialogue/choice).
  const activeStep = activeQuest ? getCurrentStep(questState, activeQuest) : null;
  // Modifiers with a non-zero value (e.g. WarriorClass: 1) for display.
  const nonZeroModifiers = useMemo(
    () => Object.entries(questState.modifiers).filter(([, value]) => value !== 0),
    [questState.modifiers]
  );
  // How many quests are available but not yet completed (shown as a badge).
  const pendingQuestCount = useMemo(
    () => visibleQuests.filter((quest) => !completedQuestIds.includes(quest.id)).length,
    [visibleQuests, completedQuestIds]
  );
  // Shorthand references to XP and derived stats.
  const explorationXp = questState.skills.explorationXp;
  const explorationLevel = useMemo(() => getLevelFromXp(explorationXp), [explorationXp]);
  const characterLevel = useMemo(() => getCharacterLevel(questState), [questState]);
  const characterClass = useMemo(() => getCharacterClass(questState.modifiers), [questState.modifiers]);
  // Find the oldest quest that hasn't been completed yet.
  // This is auto-expanded in the Quests tab so the player sees what to do next.
  const oldestPendingQuestId = useMemo(() => {
    const pending = visibleQuests.filter((quest) => !completedQuestIds.includes(quest.id));
    if (pending.length === 0) return null;
    return [...pending].sort((a, b) => a.createdAt - b.createdAt)[0].id;
  }, [visibleQuests, completedQuestIds]);
  // The "current time" adjusted by the dev fast-forward offset.
  const effectiveNow = Date.now() + devDayOffsetMs;
  // Calculate which game day it is (Day 1, Day 2, etc.) based on how many
  // real-world days have passed since the character was created.
  const dayCounter = useMemo(() => {
    if (!characterStartTimestamp) return 1;
    const elapsed = Math.max(0, effectiveNow - characterStartTimestamp);
    return Math.max(1, Math.floor(elapsed / DAY_IN_MS) + 1);
  }, [characterStartTimestamp, effectiveNow]);

  // ─── useEffect #7: Save to Nostr when a quest is completed ───────
  // We compare the current completed count to the previous render's count.
  // If it went up, the player just finished a quest → save to Nostr.
  useEffect(() => {
    if (!isQuestStateHydrated) return;
    if (completedQuestIds.length > completedQuestCountRef.current) {
      void persistQuestCheckpoint(questState);
    }
    completedQuestCountRef.current = completedQuestIds.length;
  }, [completedQuestIds, isQuestStateHydrated, questState]);

  // ─── useEffect #8: Grant daily passive XP ───────────────────────
  // Each real-world day that passes grants the character 1440 XP
  // (simulating the character "exploring" while you're away).
  // If the player hasn't logged in for 3 days, they get 3 × 1440 XP at once.
  useEffect(() => {
    if (!isQuestStateHydrated) return;
    if (dayCounter <= questState.lastDailyXpDay) return; // Already granted today.

    const daysToGrant = dayCounter - questState.lastDailyXpDay;
    const xpToGrant = daysToGrant * DAILY_XP;
    const updatedState = {
      ...questState,
      experience: questState.experience + xpToGrant,
      skills: {
        ...questState.skills,
        explorationXp: questState.skills.explorationXp + xpToGrant,
      },
      lastDailyXpDay: dayCounter,
    };

    setQuestState(updatedState);
    void persistQuestCheckpoint(updatedState);
  }, [dayCounter, isQuestStateHydrated, questState]);

  // ─── useEffect #9: Auto-expand the oldest pending quest ─────────
  // When the available quest list changes, automatically open (expand) the
  // oldest incomplete quest so the player knows what to do next.
  useEffect(() => {
    setExpandedQuestId(oldestPendingQuestId);
  }, [oldestPendingQuestId]);

  // ─── useEffect #10: Seed the first dialogue line ─────────────────
  // If the dialogue log is empty and there's an active quest, add the first
  // narrator line (e.g. "You find yourself in a forest.").
  useEffect(() => {
    if (questState.dialogueLog.length > 0) return;
    const quest = questById[questState.activeQuestId ?? ''];
    if (!quest) return;
    setQuestState((prev) => {
      if (prev.dialogueLog.length > 0) return prev;
      const started = startQuest(prev, quest);
      const firstStep = getCurrentStep(started, quest);
      return {
        ...started,
        dialogueLog: [
          appendDialogue('Narrator', interpolateStepText(firstStep.text, started.playerName)),
        ],
      };
    });
  }, [questState.activeQuestId, questState.dialogueLog.length]);

  // ─── Event Handlers ───────────────────────────────────────────────
  // These functions run when the player clicks buttons or submits forms.

  // Wipe all local progress and start fresh.
  const handleResetStory = () => {
    localStorage.removeItem(questStateStorageKey);
    setQuestState(createInitialQuestState());
    setNameInput('');
    setNameInputError(null);
    setEventLog(mockEventLog);
  };

  // Log out and go back to the title screen.
  const handleLogout = async () => {
    await logout();
    navigate('/');
  };

  // Helper: create a new dialogue entry with a unique ID.
  // The ID is used by React's "key" prop to track list items efficiently.
  const appendDialogue = (speaker: string, text: string) => ({
    id: `${speaker}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    speaker,
    text,
  });

  // Called when the player taps "Track Quest" in the Quests tab.
  // Sets the quest as active and adds its first dialogue line.
  const handleStartQuest = (questId: string) => {
    const quest = questById[questId];
    if (!quest) return;
    setQuestState((prev) => {
      const started = startQuest(prev, quest);
      const firstStep = getCurrentStep(started, quest);
      return {
        ...started,
        dialogueLog: [
          ...started.dialogueLog,
          appendDialogue('Narrator', interpolateStepText(firstStep.text, started.playerName)),
        ],
      };
    });
    setNameInput('');
    setNameInputError(null);
  };

  // Save quest progress to both localStorage AND Nostr (if logged in).
  // Called after quest completion and daily XP grants.
  const persistQuestCheckpoint = async (state: typeof questState) => {
    localStorage.setItem(questStateStorageKey, JSON.stringify(state));
    if (!user) return;
    try {
      await publishQuestStateSnapshot(nostr, user.signer, state);
    } catch (error) {
      console.warn('Failed to publish quest checkpoint to Nostr.', error);
    }
  };

  // Called when the player picks one of the dialogue choices.
  // 1. Apply the choice to the quest state (may change modifiers/flags).
  // 2. Add the player's line and the narrator's response to the dialogue log.
  const handleStepChoice = (choiceId: string) => {
    if (!activeQuest) return;
    setQuestState((prev) => {
      const currentStep = getCurrentStep(prev, activeQuest);
      if (currentStep.type !== 'choice') return prev;
      const selectedChoice = currentStep.choices.find((choice) => choice.id === choiceId);
      if (!selectedChoice) return prev;

      const nextState = applyChoice(prev, activeQuest, choiceId);
      const nextStep = getCurrentStep(nextState, activeQuest);
      const nextLog = [
        ...nextState.dialogueLog,
        appendDialogue('You', selectedChoice.label),
      ];

      if (nextStep.type === 'message') {
        nextLog.push(appendDialogue('Narrator', interpolateStepText(nextStep.text, nextState.playerName)));
      } else if (!nextState.progressByQuestId[activeQuest.id]?.isCompleted) {
        nextLog.push(appendDialogue('Narrator', interpolateStepText(nextStep.text, nextState.playerName)));
      }

      const updatedState = {
        ...nextState,
        dialogueLog: nextLog,
      };
      return updatedState;
    });
    if (activeQuest.id === 'quest-002-boar-ambush') {
      setEventLog((prev) => {
        if (prev.includes('You fended off a wild boar!')) return prev;
        return [...prev, 'You fended off a wild boar!'];
      });
    }
  };

  // Called when the player submits their character name.
  // For Quest 001 specifically, this also completes the quest, sets the
  // 'quest001-complete' flag, and shows the developer welcome message.
  const handleNameSubmit = () => {
    if (!activeQuest) return;
    const { nextState, error } = submitPlayerName(questState, activeQuest, nameInput);
    if (error) {
      setNameInputError(error);
      return;
    }
    setNameInputError(null);
    const nextStep = getCurrentStep(nextState, activeQuest);
    const submittedName = nameInput.trim();

    if (activeQuest.id === 'quest-001-origin') {
      const updatedState = {
        ...nextState,
        activeQuestId: null,
        flags: Array.from(new Set([...nextState.flags, 'quest001-complete'])),
        progressByQuestId: {
          ...nextState.progressByQuestId,
          [activeQuest.id]: {
            ...nextState.progressByQuestId[activeQuest.id],
            isCompleted: true,
          },
        },
        dialogueLog: [
          ...nextState.dialogueLog,
          appendDialogue('You', submittedName),
          appendDialogue('Narrator', interpolateStepText(nextStep.text, nextState.playerName)),
          appendDialogue('Dev Message', INTRO_DEV_MESSAGE),
        ],
      };
      setQuestState(updatedState);
      void persistQuestCheckpoint(updatedState);
      setEventLog((prev) => [
        ...prev,
        `You remembered your name is ${submittedName}`,
        `${submittedName} is exploring the Forest.`,
      ]);
      return;
    }

    const updatedState = {
      ...nextState,
      dialogueLog: [
        ...nextState.dialogueLog,
        appendDialogue('You', submittedName),
        appendDialogue('Narrator', interpolateStepText(nextStep.text, nextState.playerName)),
      ],
    };
    setQuestState(updatedState);
    void persistQuestCheckpoint(updatedState);
  };

  // ─── Navigation Bar Configuration ─────────────────────────────────
  // The five tabs shown at the bottom of the phone frame.
  // "isPrimary" makes the Play button taller with an accent border.
  const navItems: Array<{ key: MobileTab; label: string; icon: string; isPrimary?: boolean }> = [
    { key: 'character', label: 'Character', icon: '◉' },
    { key: 'quests', label: 'Quests', icon: '☰' },
    { key: 'play', label: 'Play', icon: '✦', isPrimary: true },
    { key: 'map', label: 'Map', icon: '◈' },
    { key: 'social', label: 'Social', icon: '◎' },
  ];

  // ═══════════════════════════════════════════════════════════════════
  //  RENDER HELPERS
  //  renderTabPanel() returns the JSX for whichever tab is active.
  //  Each tab is an if-block that returns its own <section>.
  // ═══════════════════════════════════════════════════════════════════
  const renderTabPanel = () => {
    // ─── CHARACTER TAB ───────────────────────────────────────────────
    // Shows the player's name, level, class, avatar, stats, skills, etc.
    if (activeTab === 'character') {
      return (
        <section className="facsimile-panel space-y-4">
          <div className="space-y-1 text-center">
            <h2 className="text-lg font-semibold text-[var(--facsimile-ink)]">
              {questState.playerName || 'Stranger'}
            </h2>
            <p className="text-[11px] uppercase tracking-[0.14em] text-[var(--facsimile-ink-muted)]">
              Level {characterLevel} Unknown {characterClass}
            </p>
          </div>
          <div className="grid grid-cols-4 gap-3">
            <div className="col-span-1">
              <img
                src={NPC_AVATAR_URL}
                alt="Character portrait"
                className="h-full w-full min-h-20 rounded-lg border border-[var(--facsimile-panel-border)] object-cover"
              />
            </div>
            <div className="col-span-3">
              <p className="text-xs text-[var(--facsimile-ink-muted)]">
                A cautious ranger from the floodplain roads, known for well-maps and steady hands.
                Travels between town and forest while carrying an unresolved oath to Ravenhall.
              </p>
            </div>
          </div>
          <p className="text-[11px] text-[var(--facsimile-ink-muted)]">
            Shareable profile link:{' '}
            <a
              href={`https://ditto.pub/${user?.pubkey ?? ''}`}
              target="_blank"
              rel="noreferrer"
              className="text-[var(--facsimile-ink)] underline decoration-[var(--facsimile-panel-border)] underline-offset-2 hover:decoration-[var(--facsimile-ink)]"
            >
              your Ditto public profile
            </a>
          </p>
          <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
            {characterStats.map(([label, value]) => (
              <div key={label} className="flex items-center justify-between border-b border-[var(--facsimile-panel-border)]/50 py-0.5">
                <p className="uppercase tracking-[0.12em] text-[var(--facsimile-ink-muted)]">{label}</p>
                <p className="text-[var(--facsimile-ink)]">{value}</p>
              </div>
            ))}
          </div>
          <div className="space-y-2 text-xs text-[var(--facsimile-ink-muted)]">
            <p><span className="text-[var(--facsimile-ink)]">Skills:</span> Exploration {explorationLevel}</p>
            <p><span className="text-[var(--facsimile-ink)]">Characteristics:</span></p>
            <p><span className="text-[var(--facsimile-ink)]">Relationships:</span></p>
            <p><span className="text-[var(--facsimile-ink)]">Affinities:</span></p>
            <p><span className="text-[var(--facsimile-ink)]">Afflictions:</span></p>
            <p><span className="text-[var(--facsimile-ink)]">Blessings:</span></p>
            <p><span className="text-[var(--facsimile-ink)]">Curses:</span></p>
            {nonZeroModifiers.length > 0 ? (
              <p>
                <span className="text-[var(--facsimile-ink)]">Modifiers:</span>{' '}
                {nonZeroModifiers.map(([name, value]) => `${name} ${value}`).join(', ')}
              </p>
            ) : null}
          </div>
        </section>
      );
    }

    // ─── QUESTS TAB ─────────────────────────────────────────────────
    // Lists all visible quests.  Tapping a quest expands it to show a
    // description and a "Track Quest" button that starts it on the Play tab.
    if (activeTab === 'quests') {
      return (
        <section className="facsimile-panel space-y-5">
          <p className="facsimile-kicker">Quests</p>
          <div className="space-y-3">
            {visibleQuests.map((quest) => {
              const isExpanded = expandedQuestId === quest.id;
              const isCompleted = completedQuestIds.includes(quest.id);

              return (
                <div key={quest.id} className="rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)]">
                  <button
                    type="button"
                    onClick={() => setExpandedQuestId(isExpanded ? null : quest.id)}
                    className="w-full px-3 py-2 text-left"
                  >
                    <p className={`text-sm ${isCompleted ? 'line-through opacity-70' : ''}`}>{quest.title}</p>
                  </button>
                  {isExpanded ? (
                    <div className="border-t border-[var(--facsimile-panel-border)] px-3 py-2">
                      <p className="text-xs text-[var(--facsimile-ink-muted)]">{quest.briefing}</p>
                      <button
                        type="button"
                        onClick={() => {
                          handleStartQuest(quest.id);
                          setActiveTab('play');
                        }}
                        className="mt-2 text-[11px] uppercase tracking-[0.14em] text-[var(--facsimile-ink)]"
                      >
                        {isCompleted ? 'Completed' : 'Track Quest'}
                      </button>
                    </div>
                  ) : null}
                </div>
              );
            })}
          </div>
        </section>
      );
    }

    // ─── MAP TAB ────────────────────────────────────────────────────
    // Shows discovered locations.  Only "Forest" for now.
    if (activeTab === 'map') {
      return (
        <section className="facsimile-panel space-y-4">
          <h2 className="text-2xl font-semibold text-[var(--facsimile-ink)]">Unknown District</h2>
          <ul className="space-y-3 text-sm text-[var(--facsimile-ink-muted)]">
            <li className="border-l border-amber-500/40 pl-3">Forest</li>
          </ul>
        </section>
      );
    }

    // ─── SOCIAL TAB ─────────────────────────────────────────────────
    // Shows real player counts (from Nostr), mock activity feed,
    // world signals, and a placeholder chat box.
    if (activeTab === 'social') {
      return (
        <section className="facsimile-panel space-y-4">
          <p className="facsimile-kicker">Social</p>
          <div className="grid grid-cols-2 gap-2">
            <div className="rounded-md border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)] px-2 py-1.5 text-center">
              <p className="text-[10px] uppercase tracking-[0.14em] text-[var(--facsimile-ink-muted)]">Strangers</p>
              <p className="text-sm text-[var(--facsimile-ink)]">{socialStats.totalPlayers}</p>
            </div>
            <div className="rounded-md border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)] px-2 py-1.5 text-center">
              <p className="text-[10px] uppercase tracking-[0.14em] text-[var(--facsimile-ink-muted)]">Kindrid Spirits</p>
              <p className="text-sm text-[var(--facsimile-ink)]">{socialStats.kindredSpirits}</p>
            </div>
          </div>
          <div className="overflow-hidden rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)]">
            <div className="facsimile-scroll max-h-64 overflow-y-auto px-3 py-2">
              <ul className="space-y-2 text-xs text-[var(--facsimile-ink-muted)]">
                {socialFeed.map((line) => (
                  <li key={line} className="border-l border-[var(--facsimile-accent)]/50 pl-2">
                    {line}
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <ul className="space-y-2 text-xs text-[var(--facsimile-ink-muted)]">
            {mockSignals.map((signal) => (
              <li key={signal} className="border-l border-[var(--facsimile-panel-border)] pl-2">
                {signal}
              </li>
            ))}
          </ul>
          <div className="rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)] p-2">
            <div className="mb-2 grid grid-cols-3 gap-1.5">
              {['Guild', 'Market', 'Player Quests'].map((label) => (
                <button
                  key={label}
                  type="button"
                  className="social-channel-button rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-[11px] text-[var(--facsimile-ink)]"
                >
                  {label}
                </button>
              ))}
            </div>
            <div className="facsimile-scroll mb-2 h-36 overflow-y-auto rounded-md bg-black/35 p-2">
              <ul className="space-y-1 text-xs text-[var(--facsimile-ink-muted)]">
                {socialChatMessages.map((line) => (
                  <li key={line}>{line}</li>
                ))}
              </ul>
            </div>
            <div className="flex items-center gap-2">
              <input
                type="text"
                placeholder="Type message..."
                className="w-full rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-xs text-[var(--facsimile-ink)] placeholder:text-[var(--facsimile-ink-muted)] focus:outline-none"
              />
              <button
                type="button"
                className="rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-xs text-[var(--facsimile-ink)]"
              >
                Send
              </button>
            </div>
          </div>
        </section>
      );
    }

    // ─── PLAY TAB (default) ─────────────────────────────────────────
    // The main gameplay view.  Has three sections stacked vertically:
    //   1. Dialogue window – scrollable chat showing quest narrative
    //   2. Event log – small bullet-point summary of recent happenings
    //   3. Location actions – buttons for interacting with the environment
    return (
      <section className="flex flex-col gap-3">
        {/* ─── Dialogue Window ─── */}
        <div
          ref={dialogueScrollRef}
          className="facsimile-scroll h-[30rem] overflow-y-auto rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)] p-2"
        >
          <div className="space-y-1">
            {questState.dialogueLog.map((line) => (
              <div key={line.id} className="dialogue-line-reveal py-0.5">
                {/* Narrator lines are italic and sky-blue */}
                {line.speaker === 'Narrator' ? (
                  <p className="text-sm leading-6 italic text-sky-200">{line.text}</p>
                ) : line.speaker === 'Dev Message' ? (
                  /* Dev messages get a distinct cyan bordered box */
                  <p className="rounded-md border border-cyan-300/55 bg-cyan-950/35 px-2 py-1 text-sm leading-6 text-cyan-100 shadow-[0_0_0_1px_rgba(34,211,238,0.15)]">
                    {line.text}
                  </p>
                ) : (
                  <p className="text-sm leading-6 text-[var(--facsimile-ink)]">
                    <span className="text-[var(--facsimile-ink-muted)]">{line.speaker}:</span> {line.text}
                  </p>
                )}
              </div>
            ))}
            {/* If there's an active quest with a current step, show the
                interactive part: choice buttons or a name-input form. */}
            {activeQuest && activeStep ? (
              <div className="dialogue-line-reveal py-0.5">
                <div className="my-1 h-px w-full bg-[var(--facsimile-panel-border)]/60" />
                {/* Choice step: show a list of clickable options */}
                {activeStep.type === 'choice' ? (
                  <div className="-mt-1">
                    <ul className="space-y-1 pl-4">
                      {activeStep.choices.map((choice) => (
                        <li key={choice.id}>
                          <button
                            type="button"
                            className="w-full text-left text-xs text-[var(--facsimile-ink-muted)] hover:text-[var(--facsimile-ink)]"
                            onClick={() => handleStepChoice(choice.id)}
                          >
                            - {choice.label}
                          </button>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}
                {/* Input step: show a text field (used for naming) */}
                {activeStep.type === 'input' ? (
                  <div className="mt-2 space-y-2">
                    <input
                      type="text"
                      value={nameInput}
                      onChange={(event) => setNameInput(event.target.value)}
                      placeholder={activeStep.placeholder}
                      className="w-full rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-xs text-[var(--facsimile-ink)] placeholder:text-[var(--facsimile-ink-muted)] focus:outline-none"
                    />
                    {nameInputError ? (
                      <p className="text-xs text-rose-300">{nameInputError}</p>
                    ) : null}
                    <button
                      type="button"
                      onClick={handleNameSubmit}
                      className="rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-xs text-[var(--facsimile-ink)]"
                    >
                      {activeStep.submitLabel}
                    </button>
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
        </div>
        {/* ─── Event Log ─── */}
        <div className="overflow-hidden rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)]">
          <div className="facsimile-scroll h-20 overflow-y-auto px-2 py-2">
            <ul className="space-y-1 pl-4 text-[11px] text-[var(--facsimile-ink-muted)]">
              {eventLog.map((eventLine) => (
                <li key={eventLine} className="list-disc">
                  {eventLine}
                </li>
              ))}
            </ul>
          </div>
        </div>
        {/* ─── Location Actions ─── */}
        <div className="rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel-soft)] p-2">
          <div className="grid grid-cols-2 gap-1.5">
            {(locationActions[currentLocation] ?? []).map((action) => (
              <button
                key={action}
                type="button"
                className={`location-action-button w-full rounded-md border border-[var(--facsimile-panel-border)] bg-[rgba(20,23,31,0.82)] px-2 py-1.5 text-left text-xs text-[var(--facsimile-ink-muted)] hover:border-[var(--facsimile-accent)] hover:text-[var(--facsimile-ink)] ${
                  action === 'Interact with Old Well' ? 'old-well-button' : ''
                }`}
              >
                {action}
              </button>
            ))}
          </div>
        </div>
      </section>
    );
  };

  // ═══════════════════════════════════════════════════════════════════
  //  MAIN JSX RETURN
  //  This is what actually gets drawn on screen.  The structure is:
  //    <main>          – full-screen dark background with radial glow
  //      <phone-frame> – 360×780 rounded container (looks like a phone)
  //        <header>    – top bar with Day counter, version, location
  //        {tab panel}  – whichever tab content is active
  //        <nav>        – bottom bar with 5 tab buttons
  // ═══════════════════════════════════════════════════════════════════
  return (
    <main className="facsimile-shell mystery-ui min-h-screen p-2 sm:p-6">
      {/* The phone-shaped container (360px wide, 780px tall, rounded corners) */}
      <div className="facsimile-phone-frame mx-auto">
        {/* Decorative glow effect behind the phone frame */}
        <div className="facsimile-glow" aria-hidden />
        {/* Scrollable content area inside the phone frame */}
        <section className="facsimile-phone-content flex w-full flex-col gap-3 px-3 py-2">
          {/* ─── Header Bar ───
              Sticky at the top.  Shows:
              - Day counter (left)        - Version number (center)
              - Current location (right)  - Dev buttons (24hr, Log out, Reset)
          */}
          <header className="sticky top-0 z-20 rounded-lg border border-[var(--facsimile-panel-border)] bg-[var(--facsimile-panel)] px-2 py-1.5 backdrop-blur">
            <div className="relative flex items-center justify-between">
              <p className="mystery-muted text-[10px] uppercase tracking-[0.2em]">Day {dayCounter}</p>
              <p className="pointer-events-none absolute left-1/2 -translate-x-1/2 text-[10px] uppercase tracking-[0.16em] text-[var(--facsimile-ink-muted)]">
                v0.4.3-dev
              </p>
              <p className="mystery-muted text-[10px] uppercase tracking-[0.2em]">{currentLocation}</p>
            </div>
            <div className="mt-1 flex items-center justify-between">
              <button
                type="button"
                onClick={() => setDevDayOffsetMs((prev) => prev + DAY_IN_MS)}
                className="rounded-md border border-[var(--facsimile-panel-border)] bg-black px-2 py-1 text-[10px] uppercase tracking-[0.16em] text-[var(--facsimile-ink)]"
              >
                24hr
              </button>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={handleLogout}
                  className="text-[10px] uppercase tracking-[0.16em] text-[var(--facsimile-ink-muted)] hover:text-[var(--facsimile-ink)]"
                >
                  Log out
                </button>
                <button
                  type="button"
                  onClick={handleResetStory}
                  className="text-[10px] uppercase tracking-[0.16em] text-[var(--facsimile-ink-muted)] hover:text-[var(--facsimile-ink)]"
                >
                  Reset Story
                </button>
              </div>
            </div>
          </header>
          {/* Render whichever tab is currently active */}
          {renderTabPanel()}
        </section>
        {/* ─── Bottom Navigation Bar ───
            Five tab buttons: Character, Quests, Play (primary), Map, Social.
            The Quests button shows a badge with the pending quest count.
        */}
        <nav className="facsimile-bottom-nav" aria-label="Primary game navigation">
          {navItems.map((item) => {
            const isActive = activeTab === item.key;
            return (
              <button
                key={item.key}
                type="button"
                onClick={() => setActiveTab(item.key)}
                className={`facsimile-nav-button relative ${item.isPrimary ? 'facsimile-nav-primary' : ''} ${isActive ? 'is-active' : ''}`}
                aria-label={item.label}
              >
                {item.key === 'quests' && pendingQuestCount > 0 ? (
                  <span className="absolute right-1.5 top-1.5 inline-flex h-4 min-w-4 items-center justify-center rounded-full border border-[var(--facsimile-accent)] bg-black px-1 text-[9px] leading-none text-[var(--facsimile-ink)]">
                    {pendingQuestCount}
                  </span>
                ) : null}
                <span className="text-base">{item.icon}</span>
                <span className="text-[10px] uppercase tracking-[0.16em]">{item.label}</span>
              </button>
            );
          })}
        </nav>
      </div>
    </main>
  );
}
